import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Mint } from "../components/Mint";
import { Connection } from "../components/Connection";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JAM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mint />
      <Connection />
    </div>
  );
}
